-- init.sql
CREATE DATABASE IF NOT EXISTS video;
USE video;
CREATE TABLE IF NOT EXISTS video (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  file_size INT NOT NULL,
  file_path VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS outbox (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  aggregate_type VARCHAR(50) NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE DATABASE IF NOT EXISTS bill;
USE bill;
CREATE TABLE IF NOT EXISTS bill (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  aggregate_type VARCHAR(50) NOT NULL,
  aggregate_id TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  event_type VARCHAR(50) NOT NULL,
  price INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON video.* TO 'mysql';
GRANT ALL PRIVILEGES ON bill.* TO 'mysql';
FLUSH PRIVILEGES;
